#! /usr/bin/env sh
$(dirname $0)/tell_slack 'danger' 'Migration failed' "@$GH_OST_HOOKS_HINT migration failed \"ALTER TABLE $GH_OST_DATABASE_NAME.$GH_OST_TABLE_NAME $GH_OST_DDL\" in $GH_OST_ELAPSED_SECONDS seconds"
